[package]
name = "ssh-config-enhance"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.5"
prettytable-rs = "0.10"
clap = { version = "4.5", features = ["derive"] }
directories = "6.0"
crossterm = "0.29"
ctrlc = "3.0"
